import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Link from 'next/link'
import { Suspense } from "react"

const inter = Inter({ subsets: ["latin"] });

async function getData() {
	const products = await fetch('https://www.papebathfittings.com/assets/products.json').then((res) => res.json())
   
	return products;
  }
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const products = await getData();
  const list = products.map((obj: any) => obj.category);
	const list2 = products.map((obj: any) => obj.range);

	const categories = Array.from(new Set(list));
	const ranges = Array.from(new Set(list2));

  return (
    <html lang="en">
      <head>
        <title>PAPE | Premium Bath Fittings</title>
        <meta content="width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no" name="viewport" />
        <meta content="" name="description" />
        <meta content="" name="author" />
        <link rel="stylesheet" href="../assets/css/e-commerce/vendor.min.css" />
        <link rel="stylesheet" href="../assets/css/e-commerce/app.min.css" />
      </head>
      <body>
        <div id="app" className="fade show">
          <div id="top-nav" className="top-nav">
            <div className="container">
              <div className="collapse navbar-collapse">
                <ul className="nav navbar-nav">
                <li><a href="/customerCare"><img src="../assets/img/flag/flag-english.png" className="flag-img" alt="" /> English </a></li>
{/*                   <li className="dropdown dropdown-hover">
                    <a href="#" data-bs-toggle="dropdown"><img src="../assets/img/flag/flag-english.png" className="flag-img" alt="" /> English <b className="caret"></b></a>
                    <ul className="dropdown-menu">
                      <li><a href="#" className="dropdown-item"><img src="../assets/img/flag/flag-english.png" className="flag-img" alt="" /> English</a></li>
                      <li><a href="#" className="dropdown-item"><img src="../assets/img/flag/flag-german.png" className="flag-img" alt="" /> German</a></li>
                      <li><a href="#" className="dropdown-item"><img src="../assets/img/flag/flag-spanish.png" className="flag-img" alt="" /> Spanish</a></li>
                      <li><a href="#" className="dropdown-item"><img src="../assets/img/flag/flag-french.png" className="flag-img" alt="" /> French</a></li>
                      <li><a href="#" className="dropdown-item"><img src="../assets/img/flag/flag-chinese.png" className="flag-img" alt="" /> Chinese</a></li>
                    </ul>
                  </li> */}
                  <li><a href="/customerCare">Customer Care</a></li>
                  {/* <li><a href="#">Order Tracker</a></li> */}
                </ul>
                <ul className="nav navbar-nav navbar-end">
                  {/* 						<li><a href="#">Career</a></li>
						<li><a href="#">Our Forum</a></li>
						<li><a href="#">Newsletter</a></li> */}
                  <li><a href="#"><i className="fab fa-facebook-f f-s-14"></i></a></li>
                  <li><a href="#"><i className="fab fa-twitter f-s-14"></i></a></li>
                  <li><a href="#"><i className="fab fa-instagram f-s-14"></i></a></li>
                  <li><a href="#"><i className="fab fa-dribbble f-s-14"></i></a></li>
                  <li><a href="#"><i className="fab fa-google f-s-14"></i></a></li>
                </ul>
              </div>
            </div>
          </div>
          <div id="header" className="header">
            <div className="container">
              <div className="header-container">
                <button type="button" className="navbar-toggle collapsed" data-bs-toggle="collapse" data-bs-target="#navbar-collapse">
                  <span className="icon-bar"></span>
                  <span className="icon-bar"></span>
                  <span className="icon-bar"></span>
                </button>
                <div className="header-logo">
                  <a href="/">
                    <span>
                      <img src="../assets/img/pape_logo.png"></img>
                    </span>
                    {/* <span className="brand-text">
                      <span>PAPE</span>
                      <small>Premium Bath Fittings</small>
                    </span> */}
                  </a>
                </div>
                <div className="header-nav">
                  <div className="collapse navbar-collapse" id="navbar-collapse">
                    <ul className="nav justify-content-center">
                      <li className="active"><a href="/">Home</a></li>
                      <li className="dropdown dropdown-full-width dropdown-hover">
                        <a href="#" data-bs-toggle="dropdown">
                          Products
                          <b className="caret"></b>
                          <span className="arrow top"></span>
                        </a>
                        <div className="dropdown-menu p-0">
                          <div className="dropdown-menu-container">
                            <div className="dropdown-menu-sidebar">
                              <h4 className="title">Shop By Collections</h4>
                              <ul className="dropdown-menu-list">
                                {ranges && ranges.map((item: any, index: any) => <li key={index}>
                                  <Link
                                    href={"/products?range="+item}
                                  >
                                    {item}
                                  </Link></li>)}
                              </ul>
                            </div>
                            <div className="dropdown-menu-content dropdown-prod-list">

                              <div className="row">
                                {categories && categories.map((cat: any) => 
                                <div className="col-lg-auto">
                                  <h4 className="title">{cat}</h4>
                                  <ul className="dropdown-menu-list">
                                    {products && products.filter((obj: any) => obj.category === cat && (obj.range === 'ARYA' || obj.range === 'HEALTH')).map((item: any, index: any) => {
                                      return <li key={index}><a href={"/products/" + item.product_id}>{item.name}</a></li>
                                    })}
                                  </ul>
                                </div>)}
                                
                              </div>
                              {/*<h4 className="title">Shop By Brand</h4>
												<ul className="dropdown-brand-list mb-0">
													<li><a href="product.html"><img src="../assets/img/brand/brand-apple.png" alt="" /></a></li>
												 	<li><a href="product.html"><img src="../assets/img/brand/brand-samsung.png" alt="" /></a></li>
													<li><a href="product.html"><img src="../assets/img/brand/brand-htc.png" alt="" /></a></li>
													<li><a href="product.html"><img src="../assets/img/brand/brand-microsoft.png" alt="" /></a></li>
													<li><a href="product.html"><img src="../assets/img/brand/brand-nokia.png" alt="" /></a></li>
													<li><a href="product.html"><img src="../assets/img/brand/brand-blackberry.png" alt="" /></a></li>
													<li><a href="product.html"><img src="../assets/img/brand/brand-sony.png" alt="" /></a></li> 
												</ul>*/}
                            </div>
                          </div>
                        </div>
                      </li>
                      <li className="dropdown dropdown-hover">
                        <a href="#" data-bs-toggle="dropdown">
                          Collections
                          <b className="caret"></b>
                          <span className="arrow top"></span>
                        </a>
                        <div className="dropdown-menu">
                        {ranges && ranges.map((item: any, index: any) => 
                                  <Link
                                  key={index}
                                  className="dropdown-item"
                                    href={"/products?range="+item}
                                  >
                                    {item}
                                  </Link>)}
                        </div>
                      </li>
                      <li><a href="/products">New Arrival</a></li>
                      {/* 								<li className="dropdown dropdown-hover">
									<a href="#" data-bs-toggle="dropdown">
										Pages
										<b className="caret"></b>
										<span className="arrow top"></span>
									</a>
									<div className="dropdown-menu">
										<a className="dropdown-item" href="index.html">Home (Default)</a>
										<a className="dropdown-item" href="index_fixed_header.html">Home (Fixed Header)</a>
										<a className="dropdown-item" href="index_inverse_header.html">Home (Inverse Header)</a>
										<a className="dropdown-item" href="search_results.html">Search Results</a>
										<a className="dropdown-item" href="product.html">Product Page</a>
										<a className="dropdown-item" href="product_detail.html">Product Details Page</a>
										<a className="dropdown-item" href="checkout_cart.html">Checkout Cart</a>
										<a className="dropdown-item" href="checkout_info.html">Checkout Shipping</a>
										<a className="dropdown-item" href="checkout_payment.html">Checkout Payment</a>
										<a className="dropdown-item" href="checkout_complete.html">Checkout Complete</a>
										<a className="dropdown-item" href="my_account.html">My Account</a>
										<a className="dropdown-item" href="contact_us.html">Contact Us</a>
										<a className="dropdown-item" href="about_us.html">About Us</a>
										<a className="dropdown-item" href="faq.html">FAQ</a>
									</div>
								</li> */}
                      <li className="dropdown dropdown-hover">
                        <a href="#" data-bs-toggle="dropdown">
                          <i className="fa fa-search search-btn"></i>
                          <span className="arrow top"></span>
                        </a>
                        <div className="dropdown-menu p-15px">
                          <form action="search_results.html" method="POST" name="search_form">
                            <div className="input-group">
                              <input type="text" placeholder="Search" className="form-control bg-light" />
                              <button className="btn btn-dark" type="submit"><i className="fa fa-search"></i></button>
                            </div>
                          </form>
                        </div>
                      </li>
                    </ul>
                  </div>
                </div>
                <div className="header-nav">
                  <ul className="nav justify-content-end">
                  <li>
                      <a href="/customerCare">
                      
                        <span className="d-none d-xl-inline"><i className="fa fa-phone"></i> Contact Us</span>
                      </a>
                    </li>
{/*                     <li className="dropdown dropdown-hover">
                      <a href="#" className="header-cart" data-bs-toggle="dropdown">
                        <i className="fa fa-shopping-bag"></i>
                        <span className="total">2</span>
                        <span className="arrow top"></span>
                      </a>
                      <div className="dropdown-menu dropdown-menu-cart p-0">
                        <div className="cart-header">
                          <h4 className="cart-title">Shopping Bag (1) </h4>
                        </div>
                        <div className="cart-body">
                          <ul className="cart-item">
                            <li>
                              <div className="cart-item-image"><img src="../assets/img/product/product-ipad.jpg" alt="" /></div>
                              <div className="cart-item-info">
                                <h4>iPad Pro Wi-Fi 128GB - Silver</h4>
                                <p className="price">$699.00</p>
                              </div>
                              <div className="cart-item-close">
                                <a href="#" data-bs-toggle="tooltip" data-bs-title="Remove">&times;</a>
                              </div>
                            </li>
                            <li>
                              <div className="cart-item-image"><img src="../assets/img/product/product-imac.jpg" alt="" /></div>
                              <div className="cart-item-info">
                                <h4>21.5-inch iMac</h4>
                                <p className="price">$1299.00</p>
                              </div>
                              <div className="cart-item-close">
                                <a href="#" data-bs-toggle="tooltip" data-bs-title="Remove">&times;</a>
                              </div>
                            </li>
                            <li>
                              <div className="cart-item-image"><img src="../assets/img/product/product-iphone.png" alt="" /></div>
                              <div className="cart-item-info">
                                <h4>iPhone 6s 16GB - Silver</h4>
                                <p className="price">$649.00</p>
                              </div>
                              <div className="cart-item-close">
                                <a href="#" data-bs-toggle="tooltip" data-bs-title="Remove">&times;</a>
                              </div>
                            </li>
                          </ul>
                        </div>
                        <div className="cart-footer">
                          <div className="row gx-2">
                            <div className="col-6">
                              <a href="checkout_cart.html" className="btn btn-default btn-theme d-block">View Cart</a>
                            </div>
                            <div className="col-6">
                              <a href="checkout_cart.html" className="btn btn-dark btn-theme d-block">Checkout</a>
                            </div>
                          </div>
                        </div>
                      </div>
                    </li>
                    <li className="divider"></li>
                    <li>
                      <a href="my_account.html">
                        <img src="../assets/img/user/user-1.jpg" className="user-img" alt="" />
                        <span className="d-none d-xl-inline">Login / Register</span>
                      </a>
                    </li> */}
                  </ul>
                </div>
              </div>
            </div>
          </div>


          <Suspense>
          {children}
          </Suspense>
          <div id="footer" className="footer">
            <div className="container">
              <div className="row">
                <div className="col-lg-3">
                  <h4 className="footer-header">ABOUT US</h4>
                  <p>
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed nec tristique dolor, ac efficitur velit. Nulla lobortis tempus convallis. Nulla aliquam lectus eu porta pulvinar. Mauris semper justo erat.
                  </p>
                  <p className="mb-lg-4 mb-0">
                    Vestibulum porttitor lorem et vestibulum pharetra. Phasellus sit amet mi congue, hendrerit mi ut, dignissim eros.
                  </p>
                </div>
                <div className="col-lg-3">
                  <h4 className="footer-header">RELATED LINKS</h4>
                  <ul className="fa-ul mb-lg-4 mb-0 p-0">
                    <li><i className="fa fa-fw fa-angle-right"></i> <a href="#">Shopping Help</a></li>
                    <li><i className="fa fa-fw fa-angle-right"></i> <a href="#">Terms of Use</a></li>
                    <li><i className="fa fa-fw fa-angle-right"></i> <a href="#">Contact Us</a></li>
                    <li><i className="fa fa-fw fa-angle-right"></i> <a href="#">Careers</a></li>
                    <li><i className="fa fa-fw fa-angle-right"></i> <a href="#">Payment Method</a></li>
                    <li><i className="fa fa-fw fa-angle-right"></i> <a href="#">Sales & Refund</a></li>
                    <li><i className="fa fa-fw fa-angle-right"></i> <a href="#">Sitemap</a></li>
                    <li><i className="fa fa-fw fa-angle-right"></i> <a href="#">Privacy & Policy</a></li>
                  </ul>
                </div>
                <div className="col-lg-3">
                  <h4 className="footer-header">LATEST PRODUCT</h4>
                  <ul className="list-unstyled list-product mb-lg-4 mb-0 p-0">
                    <li>
                      <div className="image">
                        <img src="../assets/img/product/product-iphone-6s.jpg" alt="" />
                      </div>
                      <div className="info">
                        <h4 className="info-title">Iphone 6s</h4>
                        <div className="price">$1200.00</div>
                      </div>
                    </li>
                    <li>
                      <div className="image">
                        <img src="../assets/img/product/product-galaxy-s6.jpg" alt="" />
                      </div>
                      <div className="info">
                        <h4 className="info-title">Samsung Galaxy s7</h4>
                        <div className="price">$850.00</div>
                      </div>
                    </li>
                    <li>
                      <div className="image">
                        <img src="../assets/img/product/product-ipad-pro.jpg" alt="" />
                      </div>
                      <div className="info">
                        <h4 className="info-title">Ipad Pro</h4>
                        <div className="price">$800.00</div>
                      </div>
                    </li>
                    <li>
                      <div className="image">
                        <img src="../assets/img/product/product-galaxy-note5.jpg" alt="" />
                      </div>
                      <div className="info">
                        <h4 className="info-title">Samsung Galaxy Note 5</h4>
                        <div className="price">$1200.00</div>
                      </div>
                    </li>
                  </ul>
                </div>
                <div className="col-lg-3">
                  <h4 className="footer-header">OUR CONTACT</h4>
                  <address className="mb-lg-4 mb-0">
                    <strong>Twitter, Inc.</strong><br />
                    1355 Market Street, Suite 900<br />
                    San Francisco, CA 94103<br /><br />
                    <abbr title="Phone">Phone:</abbr> (123) 456-7890<br />
                    <abbr title="Fax">Fax:</abbr> (123) 456-7891<br />
                    <abbr title="Email">Email:</abbr> <a href="mailto:sales@myshop.com">sales@myshop.com</a><br />
                    <abbr title="Skype">Skype:</abbr> <a href="skype:myshop">myshop</a>
                  </address>
                </div>
              </div>
            </div>
          </div>

          <div id="footer-copyright" className="footer-copyright">
            <div className="container">
              <div className="payment-method">
                <img src="../assets/img/payment/payment-method.png" alt="" />
              </div>
              <div className="copyright">
                Copyright &copy; 2023 SeanTheme. All rights reserved.
              </div>
            </div>
          </div>
        </div>

      </body>
    </html>
  );
}
